# The URL the site will be built for
base_url = "https://hemomorphic.alexblood.net"

# theme
#theme = "zola-hacker"

# The title of the site
title = "Hemo-Morphic"

# The description of the site
description = "Static dispatch in my bloodstream"

author = "Alex Blood"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the HTML when building the site
minify_html = false

# Whether to generate an Atom feed
generate_feeds = true

# Taxonomies
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "charcoal"

# Whether to render emojis
render_emoji = true

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
bottom_footnotes = true

[extra]
title_separator = "|" # set as |, -, _, etc

# The path to the logo of the site
logo = "images/logo.png"

# Google Analytics tracking ID
google_analytics = "example-tracking-id"

# Contact form script id that points to google macros (e.g. https://script.google.com/macros/s/<script-identifier>/exec)
contact_form_script_id = "<script-identifier>"

# Visitor notifier based on IFTTT + Webhooks. Sample here - /static/js/monitor.js
monitor = false

# Menu items
menu = [{ url = "/about", name = "About" }, { url = "/tags", name = "Tags" }]

language_code = "en-US"

# Enable OpenGraph metadata
opengraph = true

timezone = "Asia/Singapore"

# Date and time format for displaying post dates. 
# If left empty, the default format will be used: "%B %e, %Y at %H:%M %Z".
# Example of a custom format: "%Y-%m-%d %H:%M:%S %z" (2024-02-04 15:30:00 +0000)
# timeformat = ""

# The path to cv file if you use cv shortcode
# cv_file = "/files/Curriculum_Vitae.pdf"

# provide link to edit page on github
edit_page = true

# Use theme specific tags page based on templates/tags.html
simplified_tags = false

# Social links
social_links = [
  { platform = "email", user_id = "mralexblood@outlook.com" },
  { platform = "github", user_id = "rpg-alex" },
]

# GitHub settings that are used to generate the edit page link
[extra.github]
username = "rpg-alex"
repo = "hemomorphic"

# Giscus settings
# Please refer to https://giscus.app/ for more information
# and don't use the same repo_id and category_id as in the example below
[extra.giscus]
repo = "rpg-alex/hemomorphic"
repo_id = "R_kgDOQVq14Q"
category = "Blog comments"
category_id = "DIC_kwDOQVq14c4CzJUG"
mapping = "pathname"
strict = 0
reactions_enabled = 1
emit_metadata = 0
input_position = "top"
theme = "transparent_dark"
lang = "en"
loading = "lazy"
crossorigin = "anonymous"

# JSON-LD metadata
[extra.bio]
links = [
  "https://github.com/rpg-alex",
]
